### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by ooahz** [panjunwen/Valine-Admin#133]
实例日志：[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the node-js-getting-started@1.0.0 start script 'node server.js'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the node-js-getting-started package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node server.js
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs node-js-getting-started
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls node-js-getting-started
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/leanengine/app/npm-debug.log
[INFO] > node-js-getting-started@1.0.0 start /home/leanengine/app
[INFO] > node server.js
[ERROR] fs.js:642
[ERROR]   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
[ERROR]                  ^
[ERROR] Error: ENOENT: no such file or directory, open '/home/leanengine/app/template/custom2/notice.ejs'
[ERROR]     at Error (native)
[ERROR]     at Object.fs.openSync (fs.js:642:18)
[ERROR]     at Object.fs.readFileSync (fs.js:510:33)
[ERROR]     at Object.<anonymous> (/home/leanengine/app/utilities/send-mail.js:24:37)
[ERROR]     at Module._compile (module.js:577:32)
[ERROR]     at Object.Module._extensions..js (module.js:586:10)
[ERROR]     at Module.load (module.js:494:32)
[ERROR]     at tryModuleLoad (module.js:453:12)
[ERROR]     at Function.Module._load (module.js:445:3)
[ERROR]     at Module.require (module.js:504:17)
[ERROR] npm ERR! Linux 4.15.0-66-generic
[ERROR] npm ERR! argv "/usr/local/nvm/versions/node/v6.17.1/bin/node" "/usr/local/bin/npm" "start"
[ERROR] npm ERR! node v6.17.1
[ERROR] npm ERR! npm  v3.10.10
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! node-js-getting-started@1.0.0 start: `node server.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the node-js-getting-started@1.0.0 start script 'node server.js'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the node-js-getting-started package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node server.js
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs node-js-getting-started
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls node-js-getting-started
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/leanengine/app/npm-debug.log
[INFO] > node-js-getting-started@1.0.0 start /home/leanengine/app
[INFO] > node server.js
[ERROR] fs.js:642
[ERROR]   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
[ERROR]                  ^
[ERROR] Error: ENOENT: no such file or directory, open '/home/leanengine/app/template/custom2/notice.ejs'
[ERROR]     at Error (native)
[ERROR]     at Object.fs.openSync (fs.js:642:18)
[ERROR]     at Object.fs.readFileSync (fs.js:510:33)
[ERROR]     at Object.<anonymous> (/home/leanengine/app/utilities/send-mail.js:24:37)
[ERROR]     at Module._compile (module.js:577:32)
[ERROR]     at Object.Module._extensions..js (module.js:586:10)
[ERROR]     at Module.load (module.js:494:32)
[ERROR]     at tryModuleLoad (module.js:453:12)
[ERROR]     at Function.Module._load (module.js:445:3)
[ERROR]     at Module.require (module.js:504:17)
[ERROR] npm ERR! Linux 4.15.0-66-generic
[ERROR] npm ERR! argv "/usr/local/nvm/versions/node/v6.17.1/bin/node" "/usr/local/bin/npm" "start"
[ERROR] npm ERR! node v6.17.1
[ERROR] npm ERR! npm  v3.10.10
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! node-js-getting-started@1.0.0 start: `node server.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the node-js-getting-started@1.0.0 start script 'node server.js'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the node-js-getting-started package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node server.js
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs node-js-getting-started
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls node-js-getting-started
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/leanengine/app/npm-debug.log
[2021-04-14T02:46:27.121Z][system] 应用启动失败: 无法访问应用的 Web 端口（Error: connect ECONNREFUSED 10.30.139.181:56989），请确保程序在 30 秒内正确地启动了 HTTP 服务
[2021-04-14T02:46:28.403Z][system] 应用启动失败: 无法访问应用的 Web 端口（Error: connect ECONNREFUSED 10.30.139.181:56989），请确保程序在 30 秒内正确地启动了 HTTP 服务
[2021-04-14T02:46:28.404Z][system] 部署发生错误：发生了 1 个错误

**Comment by xiyuvi** [comment]
npm ERR! Linux 5.4.0-75-generic
npm ERR! argv "/usr/local/nvm/versions/node/v6.17.1/bin/node" "/usr/local/bin/npm" "install" "--production" "--https-proxy=http://proxy.leancloud.cn:8080" "--proxy=http://proxy.leancloud.cn:8080"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! path /home/leanengine/app/node_modules/.staging/@types/superagent-c06d612f/package.json
npm ERR! code ENOTDIR
npm ERR! errno -20
npm ERR! syscall open

npm ERR! ENOTDIR: not a directory, open '/home/leanengine/app/node_modules/.staging/@types/superagent-c06d612f/package.json'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/leanengine/app/npm-debug.log
The command '/bin/sh -c npm install --production --https-proxy=http://proxy.leancloud.cn:8080 --proxy=http://proxy.leancloud.cn:8080' returned a non-zero code: 236
