### ISSUE TITLE
邮件提醒报错，不知道为什么Error: undefined is not a valid uri or options object.

### ISSUE THREAD

**Issue by ZHYCarge** [panjunwen/Valine-Admin#138]
错误代码如下：
```
[2021-07-16T12:06:00.462136600Z][instance:web1] LeanEngine: /self_wake: 500: Error: undefined is not a valid uri or options object.
[2021-07-16T12:06:00.462165000Z][instance:web1]     at request (/home/leanengine/app/node_modules/request/index.js:44:11)
[2021-07-16T12:06:00.462170400Z][instance:web1]     at /home/leanengine/app/cloud.js:70:5
[2021-07-16T12:06:00.462173700Z][instance:web1]     at promiseTry.then.user (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:198:14)
[2021-07-16T12:06:00.462177500Z][instance:web1]     at processTicksAndRejections (internal/process/task_queues.js:86:5)
[2021-07-16T12:06:00.467000000Z][system] CloudQueue 运行失败 a3d3fbac-6b17-4899-bd60-949fdc8223b8: self_wake !! {"error":"500 - {\"code\":1,\"error\":\"undefined is not a valid uri or options object.\"}"}
```
#### 自动唤醒函数配置（感觉不是这里报错的
![image](https://user-images.githubusercontent.com/40520292/125945473-56c05e12-bc50-40b6-bb93-d7b13fcb90b5.png)
#### 相关参数配置
![image](https://user-images.githubusercontent.com/40520292/125945631-5415b38a-650f-426e-8eeb-06e3673ba8b9.png)
（我相信我打码打了个寂寞2333
**有大佬能看看嘛（暴风哭泣**

**Comment by DesertsP** [comment]
有绑定云引擎的域名吗？

**Comment by ZHYCarge** [comment]
> 有绑定云引擎的域名吗？
大佬，有的
![image](https://user-images.githubusercontent.com/40520292/125946925-3c473bc9-d80c-4d4b-acf4-b4f9d5d156ef.png)

**Comment by DesertsP** [comment]
ADMIN_URL这个环境变量设置下，具体可以搜索教程里的，之后重启容器

**Comment by ZHYCarge** [comment]
> ADMIN_URL这个环境变量设置下，具体可以搜索教程里的，之后重启容器

可以了，感谢大佬（以为那个变量不是必须的orz
