### ISSUE TITLE
SMTP邮箱配置异常

### ISSUE THREAD

**Issue by tiexo** [panjunwen/Valine-Admin#16]
```
STDOUT web1 13:05:26
> Valine-Admin@1.0.0 start /home/leanengine/app
STDOUT web1 13:05:26
> node server.js
STDOUT web1 13:05:26

STDOUT web1 13:05:28
    at SMTPConnection._responseActions.push.str (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:366:26)
STDOUT web1 13:05:28
Node app is running on port: 3000
STDOUT web1 13:05:28
SMTP邮箱配置异常： { Error: Invalid login: 535 Error: ÇëÊ¹ÓÃÊÚÈ¨ÂëµÇÂ¼¡£ÏêÇéÇë¿´: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
STDOUT web1 13:05:28
    at SMTPConnection._formatError (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
STDOUT web1 13:05:28
    at SMTPConnection._processResponse (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
STDOUT web1 13:05:28
    at SMTPConnection._onData (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
STDOUT web1 13:05:28
    at TLSSocket._socket.on.chunk (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)
STDOUT web1 13:05:28
    at emitOne (events.js:96:13)
STDOUT web1 13:05:28
    at readableAddChunk (_stream_readable.js:176:18)
STDOUT web1 13:05:28
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
STDOUT web1 13:05:28
    at TLSWrap.onread (net.js:559:20)
STDOUT web1 13:05:28
  code: 'EAUTH',
STDOUT web1 13:05:28
  response: '535 Error: ÇëÊ¹ÓÃÊÚÈ¨ÂëµÇÂ¼¡£ÏêÇéÇë¿´: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256',
STDOUT web1 13:05:28
  responseCode: 535,
STDOUT web1 13:05:28
  command: 'AUTH PLAIN' }
STDOUT web1 13:05:28
实例启动成功：{"runtime":"nodejs-v6.14.4","version":"3.3.2"}
```

**Comment by tiexo** [comment]
昨晚还是好的，今天突然出问题了...
我尝试了三四遍用QQ邮箱生成的授权码登录，并且重启实例，依然会报错。
实在没找到自己哪里设置错了

**Comment by panjunwen** [comment]
看起来是QQ邮箱那边的问题

**Comment by panjunwen** [comment]
QQ邮箱炸了，只要重启了实例就会无法登录，先不要折腾了

**Comment by tiexo** [comment]
@panjunwen 原来乳此....多谢。

**Comment by panjunwen** [comment]
@tiexo 经过折腾发现，QQ邮箱很神奇，会限制部分设备SMTP正常授权，通常云引擎重启等操作会导致IP更改，QQ邮箱就死活不让发件了。我的主站的云引擎和测试站用了相同的配置，主站重启云引擎后就再也没法发件了。但另一个云引擎完全正常。此外，我本地测试QQ邮箱的授权码登录也是时好时坏。

**Comment by tiexo** [comment]
@panjunwen 晕，有没有哪个稳定邮箱推荐的。

**Comment by panjunwen** [comment]
@tiexo 我这里改用微软的Outlook了，但是也是一番折腾，需要在https://account.live.com/activity 上把云引擎的IP标注为安全。应该是触发了邮箱的安全机制，禁止异地登录。

**Comment by tiexo** [comment]
我也用outlook
