### ISSUE TITLE
邮件提醒报错 501

### ISSUE THREAD

**Issue by MeowCold** [panjunwen/Valine-Admin#62]
开始部署 20181209-223839 到 web1
STDOUT  00:17:47
正在创建新实例 ...
STDOUT  00:17:49
正在启动新实例 ...
STDOUT web1 00:17:50

STDOUT web1 00:17:50
> Valine-Admin@1.0.0 start /home/leanengine/app
STDOUT web1 00:17:50
> node server.js
STDOUT web1 00:17:50

STDOUT web1 00:17:53
Node app is running on port: 3000
STDOUT  00:17:54
实例启动成功：{"runtime":"nodejs-v6.15.1","version":"3.3.2"}
STDOUT  00:17:54
正在更新云函数信息 ...
STDOUT  00:17:54
部署完成：1 个实例部署成功
STDOUT web1 00:17:59
SMTP邮箱配置正常！
STDOUT web1 00:18:14
IP: 10.10.9.200
STDOUT web1 00:18:14
这条评论没有 @ 任何人
STDOUT web1 00:18:16
{ Error: Mail command failed: 501 5.1.7 Bad address mailbox syntax.
STDOUT web1 00:18:16
    at SMTPConnection._formatError (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:605:19)
STDOUT web1 00:18:16
    at SMTPConnection._actionMAIL (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:1370:34)
STDOUT web1 00:18:16
    at SMTPConnection._responseActions.push.str (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:857:18)
STDOUT web1 00:18:16
    at SMTPConnection._processResponse (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:764:20)
STDOUT web1 00:18:16
    at SMTPConnection._onData (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:570:14)
STDOUT web1 00:18:16
    at TLSSocket._socket.on.chunk (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:522:47)
STDOUT web1 00:18:16
    at emitOne (events.js:96:13)
STDOUT web1 00:18:16
    at TLSSocket.emit (events.js:188:7)
STDOUT web1 00:18:16
    at readableAddChunk (_stream_readable.js:176:18)
STDOUT web1 00:18:16
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
STDOUT web1 00:18:16
    at TLSWrap.onread (net.js:559:20)
STDOUT web1 00:18:16
  code: 'EENVELOPE',
STDOUT web1 00:18:16
  response: '501 5.1.7 Bad address mailbox syntax.',
STDOUT web1 00:18:16
  responseCode: 501,
STDOUT web1 00:18:16
  command: 'MAIL FROM' }
STDOUT web1 00:18:19
垃圾评论检测完成，放行~
![TIM截图20190913003425](https://user-images.githubusercontent.com/7279597/64802928-52226880-d5be-11e9-99be-b489e1c42b16.png)

**Comment by DesertsP** [comment]
邮箱配置不对，请提供配置参数

**Comment by zwxo** [comment]
解决了吗，我也遇到这个问题

**Comment by MeowCold** [comment]
@zw-space 没在leancloud部署了，你看看其他部署平台

**Comment by zwxo** [comment]
好的，谢谢




你
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DesertsP/Valine-Admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 凌晨1:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DesertsP/Valine-Admin] 邮件提醒报错 501 (#62)





 
@zw-space 没在leancloud部署了，你看看其他部署平台
